<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="AutoExtrusion" Id="{86502c01-c062-40ed-a59d-dbd5307352d9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AutoExtrusion
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AutoExtrusion">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>