<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="ControlTemp" Id="{0e8e534b-cf5f-4841-8555-305e5ee6bfa8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM ControlTemp
VAR
	FB_CTRL_TempControllerTop: FB_CTRL_TempController;
	FB_CTRL_TempControllerBot: FB_CTRL_TempController;
	modo:E_CTRL_MODE:=eCTRL_MODE_ACTIVE;
	
	sControllerParameter: ST_CTRL_TempCtrlParameter:=
	(
			(* general parameters *)
			iMode                     :=1,
			bSelCtrlParameterSet      :=TRUE,
			tCtrlCycleTime            :=T#100MS,
			tTaskCycleTime            :=T#10MS,

		  (* tuning parameteer *)
		  iTuningMode               := eCTRL_TuneMode_HEATING,
		  tTuneStabilisation        := T#30S,
		  fEndTunePercentHeating    := 80.0,
		  fYTuneHeating:=100.0,
		  fEndTunePercentCooling    := 20.0,
		  fYStableCooling:=50.0,
		  fScalingFactor            := 1.0,
		
		  (* setpoint parameters *)
		  fWMin:=0.0,
		  fWMax:=573.0,

		  (* start up *)
		  bEnableSoftStart:=FALSE,
		  bEnableRamping:=TRUE,
		  fWStartUp:=348.0,
		  tStartUp:=T#30S,
		  bStartUpRamping:=TRUE,
		  fWStartUpVeloPos:=3.0,
		  fWStartUpVeloNeg:=3.0,
		  fWVeloPos:=5.0,
		  fWVeloNeg:=5.0,
		
		  (* actual value parameters *)
		  bFilter:=FALSE,
		  tFilter:=T#100MS,
		
		  (* deadband parameters *)
		  bDeadband:=FALSE,
		  fEDeadband:=1.0,
		  
		  (* control value parameters *)
		  fYMin:=0.0,
		  fYMax:=573.0,
		  fYManual:=20.0,
		  fYOnFailure:=20.0,
		  tPWMCycleTime:=T#100MS,
		  tPWMMinOffTime:=T#100MS,
		  tPWMMinOnTime:=T#100MS,
		  tPWMWaitingTime:=T#100MS,
		  fYThresholdOff:=50.0,
		  fYThresholdOn:=50.0,
		  nCyclesForSwitchOver      := 100,
		
		  (* controller settings *)
		  bEnablePreController:=FALSE,
		  bEnableZones:=FALSE,
		  bEnableCVFilter:=FALSE,
		  iFilterType:=eCTRL_FilterType_AVERAGE,
		  iControllerType:=eCTRL_ControllerType_PID,
		
		  (* min max temperatures *)
		  TempLow:=283.0,
		  TempLowLow:=0.0,
		  TempHigh:=503.0,
		  TempHighHigh:=523.0,
		  TempAbsoluteHigh:=523.0,
		  TempAbsoluteLow:=0.0,
		
		  (* internal tuning parameters *)
		  fTuneKp                   := 1.2,
		  fTuneTn                   := 2.0,
		  fTuneTv                   := 0.42,
		  fTuneTd                   := 0.25
  );
		
	//sControllerParameter
	sControllerParameter2:ST_CTRL_TempCtrlParameter:=
	(
		(* base *)
		tCtrlCycleTime := T#1000MS,
		tTaskCycleTime := T#10MS,
		
		fYMin := -100,
		fYMax := 100,
		tPWMCycleTime := T#100MS ,
		fYManual := 20,
		bFilter := FALSE,
		tFilter := T#100MS,
		bDeadband := FALSE,
		fEDeadband := 1.0, (* deadband *)
		fWMin := 288,
		fWMax := 523,
		fWStartUp := 323,
		tStartUp := T#1S,
		fWVeloPos := 0.5,
		fWVeloNeg := 0.5,
		bStartUpRamping := TRUE,
		fWStartUpVeloPos := 0.5,
		fWStartUpVeloNeg := 0.5,
		iMode := eCTRL_ControlMode_HEATING,
		dwAlarmSupp := 16#FF_FF_FF_FF,
		bSelCtrlParameterSet:= FALSE,
		
		(* tuninig *)
		iTuningMode := eCTRL_TuneMode_heating,
		fYTuneHeating := 100.0,
		fYTuneCooling := -100.0,
		fEndTunePercentHeating := 80.0, (* switch to closed loop control when X > 0.8*W *)
		fEndTunePercentCooling := -70.0, (* switch to closed loop control when X < 0.2*W *)
		iReactionOnFailure := eCTRL_ReactionOnFailure_StopController,
		TempLow := -50.0,
		TempLowLow := -100.0,
		TempHigh := 523,
		TempHighHigh := 523,
		TempAbsoluteHigh := 523,
		TempAbsoluteLow := -95.0,
		bEnablePreController := FALSE,
		bEnableZones := FALSE,
		bEnableCVFilter := FALSE,
		iFilterType := eCTRL_FilterType_AVERAGE,
		iControllerType := eCTRL_ControllerType_PID
	);
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"FB_CTRL_TempController"</v>
                      <o n="Instance" t="Operand">
                        <v n="Operand">"FB_CTRL_TempControllerTop"</v>
                        <v n="Type">"FB_CTRL_TempController"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">16L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <n />
                          <o>
                            <v n="Operand">"IO.Q_HeaterT"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">18L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">19L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">20L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">21L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">22L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">23L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">24L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">26L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">28L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">31L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">32L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"modo"</v>
                            <v n="Type">"E_CTRL_MODE"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">9L</v>
                          </o>
                          <v n="Id">8L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"FALSE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">11L</v>
                          </o>
                          <v n="Id">10L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"0.9*GVL.TempExtrusion"</v>
                            <v n="Type">"LREAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">34L</v>
                          </o>
                          <v n="Id">33L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"0.9*GVL.TempExtrusion"</v>
                            <v n="Type">"LREAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">36L</v>
                          </o>
                          <v n="Id">35L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"GVL.TempTerT"</v>
                            <v n="Type">"LREAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">38L</v>
                          </o>
                          <v n="Id">37L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">40L</v>
                          </o>
                          <v n="Id">39L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">42L</v>
                          </o>
                          <v n="Id">41L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">44L</v>
                          </o>
                          <v n="Id">43L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">46L</v>
                          </o>
                          <v n="Id">45L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">48L</v>
                          </o>
                          <v n="Id">47L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">50L</v>
                          </o>
                          <v n="Id">49L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">52L</v>
                          </o>
                          <v n="Id">51L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">54L</v>
                          </o>
                          <v n="Id">53L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"sControllerParameter"</v>
                            <v n="Type">"ST_CTRL_TempCtrlParameter"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">56L</v>
                          </o>
                          <v n="Id">55L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>eCtrlMode</v>
                          <v>bSelSetpoint</v>
                          <v>fW1</v>
                          <v>fW2</v>
                          <v>fX</v>
                          <v>fYManual</v>
                          <v>bOpenThermocouple</v>
                          <v>bReverseThermocouple</v>
                          <v>bBackVoltage</v>
                          <v>bLeakage</v>
                          <v>bShortCircuit</v>
                          <v>bOpenCircuit</v>
                          <v>sParaControllerExternal</v>
                          <v>sControllerParameter</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>E_CTRL_MODE</v>
                          <v>BOOL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>ST_CTRL_ParaController</v>
                          <v>ST_CTRL_TempCtrlParameter[REF]</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>fYAnalog</v>
                          <v>bYPWMPos</v>
                          <v>bYPWMNeg</v>
                          <v>bYDigPos</v>
                          <v>bYDigNeg</v>
                          <v>dwAlarm</v>
                          <v>fMaxOverShoot</v>
                          <v>tStartUpTime</v>
                          <v>eCtrlState</v>
                          <v>sParaControllerInternal</v>
                          <v>bError</v>
                          <v>eErrorId</v>
                          <v>fYP</v>
                          <v>fYI</v>
                          <v>fYD</v>
                          <v>fTempVelo</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>LREAL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>DWORD</v>
                          <v>LREAL</v>
                          <v>TIME</v>
                          <v>E_CTRL_STATE</v>
                          <v>ST_CTRL_ParaController</v>
                          <v>BOOL</v>
                          <v>E_CTRL_ErrorCodes</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">FunctionBlock</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">17L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"FB_CTRL_TempController"</v>
                      <o n="Instance" t="Operand">
                        <v n="Operand">"FB_CTRL_TempControllerBot"</v>
                        <v n="Type">"FB_CTRL_TempController"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">106L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <n />
                          <o>
                            <v n="Operand">"IO.Q_HeaterB"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">108L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">109L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">110L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">111L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">112L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">113L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">114L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">115L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">116L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">117L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">118L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">119L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">120L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">121L</v>
                          </o>
                          <o>
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">122L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"modo"</v>
                            <v n="Type">"E_CTRL_MODE"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">124L</v>
                          </o>
                          <v n="Id">123L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"FALSE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">126L</v>
                          </o>
                          <v n="Id">125L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"GVL.TempExtrusion"</v>
                            <v n="Type">"REAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">128L</v>
                          </o>
                          <v n="Id">127L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"GVL.TempExtrusion"</v>
                            <v n="Type">"REAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">130L</v>
                          </o>
                          <v n="Id">129L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"GVL.TempTerB"</v>
                            <v n="Type">"LREAL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">132L</v>
                          </o>
                          <v n="Id">131L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">134L</v>
                          </o>
                          <v n="Id">133L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">136L</v>
                          </o>
                          <v n="Id">135L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">138L</v>
                          </o>
                          <v n="Id">137L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">140L</v>
                          </o>
                          <v n="Id">139L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">142L</v>
                          </o>
                          <v n="Id">141L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">144L</v>
                          </o>
                          <v n="Id">143L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">146L</v>
                          </o>
                          <v n="Id">145L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">""</v>
                            <n n="Type" />
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">148L</v>
                          </o>
                          <v n="Id">147L</v>
                        </o>
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"sControllerParameter"</v>
                            <v n="Type">"ST_CTRL_TempCtrlParameter"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">150L</v>
                          </o>
                          <v n="Id">149L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>eCtrlMode</v>
                          <v>bSelSetpoint</v>
                          <v>fW1</v>
                          <v>fW2</v>
                          <v>fX</v>
                          <v>fYManual</v>
                          <v>bOpenThermocouple</v>
                          <v>bReverseThermocouple</v>
                          <v>bBackVoltage</v>
                          <v>bLeakage</v>
                          <v>bShortCircuit</v>
                          <v>bOpenCircuit</v>
                          <v>sParaControllerExternal</v>
                          <v>sControllerParameter</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>E_CTRL_MODE</v>
                          <v>BOOL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>ST_CTRL_ParaController</v>
                          <v>ST_CTRL_TempCtrlParameter[REF]</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>fYAnalog</v>
                          <v>bYPWMPos</v>
                          <v>bYPWMNeg</v>
                          <v>bYDigPos</v>
                          <v>bYDigNeg</v>
                          <v>dwAlarm</v>
                          <v>fMaxOverShoot</v>
                          <v>tStartUpTime</v>
                          <v>eCtrlState</v>
                          <v>sParaControllerInternal</v>
                          <v>bError</v>
                          <v>eErrorId</v>
                          <v>fYP</v>
                          <v>fYI</v>
                          <v>fYD</v>
                          <v>fTempVelo</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>LREAL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>BOOL</v>
                          <v>DWORD</v>
                          <v>LREAL</v>
                          <v>TIME</v>
                          <v>E_CTRL_STATE</v>
                          <v>ST_CTRL_ParaController</v>
                          <v>BOOL</v>
                          <v>E_CTRL_ErrorCodes</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                          <v>LREAL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">FunctionBlock</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">107L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">105L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>