//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircularSeasManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlertResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CircularSeasManager.Resources.AlertResources", typeof(AlertResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select all the parameters.
        /// </summary>
        internal static string AllParametersMustProvide {
            get {
                return ResourceManager.GetString("AllParametersMustProvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File available for printing from local files.
        /// </summary>
        internal static string CanPrintedFromLocal {
            get {
                return ResourceManager.GetString("CanPrintedFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant&apos;t delete a file which is being printed.
        /// </summary>
        internal static string DeletingBodyErrorProcesing {
            get {
                return ResourceManager.GetString("DeletingBodyErrorProcesing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a file to delete.
        /// </summary>
        internal static string DeletingBodySelectOne {
            get {
                return ResourceManager.GetString("DeletingBodySelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting failure.
        /// </summary>
        internal static string DeletingHeader {
            get {
                return ResourceManager.GetString("DeletingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string DeletingReturn {
            get {
                return ResourceManager.GetString("DeletingReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Come to main menu.
        /// </summary>
        internal static string DisconnectedBack {
            get {
                return ResourceManager.GetString("DisconnectedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can`t connect to Octoprint.
        /// </summary>
        internal static string DisconnectedBody {
            get {
                return ResourceManager.GetString("DisconnectedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error.
        /// </summary>
        internal static string DisconnectedHeader {
            get {
                return ResourceManager.GetString("DisconnectedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait.
        /// </summary>
        internal static string DisconnectedWait {
            get {
                return ResourceManager.GetString("DisconnectedWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No file has been provided.
        /// </summary>
        internal static string FileNotProvided {
            get {
                return ResourceManager.GetString("FileNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Identifier.
        /// </summary>
        internal static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order registered successfully.
        /// </summary>
        internal static string OrderRegistered {
            get {
                return ResourceManager.GetString("OrderRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order.
        /// </summary>
        internal static string OrderStock {
            get {
                return ResourceManager.GetString("OrderStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Out of stock.
        /// </summary>
        internal static string OutStock {
            get {
                return ResourceManager.GetString("OutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There aren&apos;t stock for this kind of filament.
        /// </summary>
        internal static string OutStockMessage {
            get {
                return ResourceManager.GetString("OutStockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request could not be completed. Try enabling support and if the problem persists, please contact an administrator..
        /// </summary>
        internal static string PerhapsSupportNeeded {
            get {
                return ResourceManager.GetString("PerhapsSupportNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printer is processing a part. wait to end first.
        /// </summary>
        internal static string PrintingBodyProcessing {
            get {
                return ResourceManager.GetString("PrintingBodyProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select one file to print.
        /// </summary>
        internal static string PrintingBodySelectOne {
            get {
                return ResourceManager.GetString("PrintingBodySelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to directly print the selected file?.
        /// </summary>
        internal static string PrintingDirectly {
            get {
                return ResourceManager.GetString("PrintingDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printing failure.
        /// </summary>
        internal static string PrintingHeaderError {
            get {
                return ResourceManager.GetString("PrintingHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string PrintingReturn {
            get {
                return ResourceManager.GetString("PrintingReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The printer is working. The file will be uploaded but you must wait for the current one to finish. Later you can select it from the local print menu.
        /// </summary>
        internal static string PrintingWorking {
            get {
                return ResourceManager.GetString("PrintingWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select one material.
        /// </summary>
        internal static string SelectMaterial {
            get {
                return ResourceManager.GetString("SelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t connect to server. Try it later.
        /// </summary>
        internal static string ServerDisconnected {
            get {
                return ResourceManager.GetString("ServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirms that you have spent 1 spool of.
        /// </summary>
        internal static string SpendOneSpool {
            get {
                return ResourceManager.GetString("SpendOneSpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploaded successfully.
        /// </summary>
        internal static string SucessUpload {
            get {
                return ResourceManager.GetString("SucessUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to confirm the order with the following data?.
        /// </summary>
        internal static string SureConfirmOrders {
            get {
                return ResourceManager.GetString("SureConfirmOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only files in .gcode format are supported. Upload failed.
        /// </summary>
        internal static string UploadOnlyGCODE {
            get {
                return ResourceManager.GetString("UploadOnlyGCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select only stl files.
        /// </summary>
        internal static string UploadOnlySTL {
            get {
                return ResourceManager.GetString("UploadOnlySTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On the desktop app, you can&apos;t scan a QR. Instead, select the order from the list displayed on the screen and then click this button to accept..
        /// </summary>
        internal static string UwpOrder {
            get {
                return ResourceManager.GetString("UwpOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On the desktop app, you can&apos;t scan a QR. Instead, select the material from the list that was displayed on the screen and then click this button to discard a spent spool..
        /// </summary>
        internal static string UwpSpoolStock {
            get {
                return ResourceManager.GetString("UwpSpoolStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string WarningHeader {
            get {
                return ResourceManager.GetString("WarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
